# Generated by Django 4.1 on 2022-08-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='linked_users',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='linked_users', to='hospital.person'),
        ),
    ]
