# Generated by Django 4.1 on 2022-08-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_linked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='linked_users',
        ),
    ]
