# Generated by Django 4.1 on 2022-08-19 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_doctor_is_doctor'),
        ('accounts', '0005_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.ForeignKey(blank=True, limit_choices_to={'Person__is_doctor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.person', unique=True),
        ),
    ]
