# Generated by Django 4.1 on 2022-08-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='durgs',
            field=models.TextField(max_length=4000, null=True, verbose_name='Durgs Taken'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comment',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
