# Generated by Django 4.1 on 2022-08-20 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14, message='invalid Id number')]),
        ),
    ]
