# Generated by Django 4.1 on 2022-08-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
