# Generated by Django 4.1 on 2022-08-19 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_medical_record_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_medical_records', to='hospital.reservation', unique=True),
        ),
    ]
