# Generated by Django 4.1 on 2022-08-20 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_person_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{14}$', 'only numbers is valid')]),
        ),
    ]
