# Generated by Django 4.1 on 2022-08-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_medical_record_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-date',)},
        ),
    ]
