# Generated by Django 4.1 on 2022-08-23 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reserves', to='hospital.doctor'),
        ),
    ]
