# Generated by Django 4.1 on 2022-08-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_reservation_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_record', to='hospital.patient'),
        ),
    ]
