# Generated by Django 4.1 on 2022-08-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_reservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_doctor',
            field=models.BooleanField(default=True),
        ),
    ]
