# Generated by Django 4.1 on 2022-08-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_medical_record_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_record',
            name='added_by',
        ),
        migrations.AddField(
            model_name='medical_record',
            name='added_doctor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_medical_records', to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_records', to='hospital.patient'),
        ),
    ]
