# Generated by Django 4.1 on 2022-08-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_medical_record_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='added_doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_medical_records', to='hospital.doctor'),
        ),
    ]
