# Generated by Django 4.1 on 2022-08-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_doctor_is_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_record',
            old_name='description',
            new_name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_doctor',
        ),
        migrations.AddField(
            model_name='medical_record',
            name='recommended_medications',
            field=models.TextField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
