# Generated by Django 4.1 on 2022-08-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_medical_record_added_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='desc',
            field=models.TextField(default='hey'),
        ),
    ]
