# Generated by Django 4.1 on 2022-08-31 22:30

from django.db import migrations, models
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_person_middle_name_alter_person_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id_number',
        ),
        migrations.AlterField(
            model_name='department',
            name='img',
            field=models.ImageField(blank=True, upload_to='images', validators=[hospital.models.check_image]),
        ),
        migrations.AlterField(
            model_name='department',
            name='logo_img',
            field=models.ImageField(blank=True, upload_to='images', validators=[hospital.models.check_image]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(blank=True, upload_to='images', validators=[hospital.models.check_image]),
        ),
    ]
