# Generated by Django 3.2.15 on 2022-08-20 04:43

from django.db import migrations, models
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_rename_description_medical_record_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='img',
            field=models.ImageField(upload_to='images', validators=[hospital.models.check_image]),
        ),
        migrations.AlterField(
            model_name='department',
            name='logo_img',
            field=models.ImageField(upload_to='images', validators=[hospital.models.check_image]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(upload_to='images', validators=[hospital.models.check_image]),
        ),
    ]
