# Generated by Django 4.1 on 2022-09-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_person_id_number_alter_department_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='endDay',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='friday', max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='startDay',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(default='Doctor', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='doctor_department', to='hospital.department'),
        ),
    ]
