# Generated by Django 4.1 on 2022-08-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_department_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='desc',
            field=models.TextField(),
        ),
    ]
