# Generated by Django 4.1 on 2022-09-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_department_endday_alter_department_startday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='endDay',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='thursday', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='startDay',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='sunday', editable=False, max_length=10),
        ),
    ]
