# Generated by Django 4.1 on 2022-08-16 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_department_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='days_Schedule',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='department',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='department',
            name='time_Schedule',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
