# Generated by Django 4.1 on 2022-08-16 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_department_days_schedule_department_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='days_Schedule',
        ),
        migrations.RemoveField(
            model_name='department',
            name='time_Schedule',
        ),
        migrations.AddField(
            model_name='department',
            name='endDay',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='friday', max_length=10),
        ),
        migrations.AddField(
            model_name='department',
            name='endTime_Schedule',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='department',
            name='startDay',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10),
        ),
        migrations.AddField(
            model_name='department',
            name='startTime_Schedule',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
