# Generated by Django 4.1 on 2022-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_department_endday_alter_department_startday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='endTime_Schedule',
            field=models.TimeField(default='17:00', editable=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='startTime_Schedule',
            field=models.TimeField(default='09:00', editable=False),
        ),
    ]
