# Generated by Django 4.1 on 2022-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_remove_department_days_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
