# Generated by Django 4.1 on 2022-08-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_doctor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
