# Generated by Django 4.1 on 2022-08-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_alter_doctor_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo_img',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
